AWSTemplateFormatVersion: 2010-09-09

Description: Root Stack for 3 nested Stacks

Parameters:
  EnvironmentType:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - qa
    - prod
  
  SubnetCidrinformationDEV:
    Description: Comma-delimited list of 6 CIDR blocks
    Type: String
    Default: "10.37.32.0/20, 10.37.43.0/24, 10.37.44.0/24, 10.37.34.0/24, 10.37.35.0/24, 10.37.38.0/24, 10.37.39.0/24 "


  SubnetCidrinformationQA:
    Description: Comma-delimited list of 6 CIDR blocks
    Type: String 
    Default: "10.37.96.0/23, 10.37.96.64/27, 10.37.97.64/27, 10.37.96.32/27, 10.37.97.32/27, 10.37.96.0/27, 10.37.97.0/27 "

  SubnetCidrinformationPROD:
    Description: Comma-delimited list of 6 CIDR blocks
    Type: String
    Default: "10.37.48.0/22, 10.37.48.128/25, 10.37.49.128/25, 10.37.50.0/25, 10.37.50.128/25, 10.37.48.0/25, 10.37.49.0/25 "
 
Resources:
  RootStackDEV:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        SubnetCidrinformation: !Ref SubnetCidrinformationDEV
      TemplateURL: https://itp-cf-ns-ak.s3.amazonaws.com/nestedstackspractice/EnvNestedStackforSubnets.yml
      TimeoutInMinutes: 5
      Tags:
      - Key: Owner
        Value: afreen.khan@intuitive.cloud

  RootStackQA:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        SubnetCidrinformation: !Ref SubnetCidrinformationQA
      TemplateURL: https://itp-cf-ns-ak.s3.amazonaws.com/nestedstackspractice/EnvNestedStackforSubnets.yml
      TimeoutInMinutes: 5
      Tags:
      - Key: Owner
        Value: afreen.khan@intuitive.cloud
        
  RootStackPROD:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        SubnetCidrinformation: !Ref SubnetCidrinformationPROD
      TemplateURL: https://itp-cf-ns-ak.s3.amazonaws.com/nestedstackspractice/EnvNestedStackforSubnets.yml
      TimeoutInMinutes: 5
      Tags:
      - Key: Owner
        Value: afreen.khan@intuitive.cloud